[project]
urls = { homepage = "http://www.control.lth.se/Staff/JerkerNordh/pyparticleest.html" }
dependencies = [
  "numpy>=2.1.2",
  "scipy>=1.14.1",
  "matplotlib>=3.9.2",
  "numba>=0.61.0,<0.63.0",
  "matplot2tikz",
  "latextable",
  "texttable",
]
name = "pyParticleEst"
authors = [{ email = "ajn@ajn.se", name = "Jerker Nordh" }]
description = "Framework for particle based estimation methods, such as particle filtering and smoothing"
license-files = ["COPYING"]
version = "1.1.4"
requires-python = ">=3.13"

[tool.setuptools]
packages = [
  "pyparticleest",
  "pyparticleest.models",
  "pyparticleest.paramest",
  "pyparticleest.utils",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "numpy>=2.1.2"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
docs = ["numpydoc>=1.7.0"]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = [
  "E",     # pycodestyle errors
  "F",     # Pyflakes
  "YTT",   # flake8-2020
  "ANN",   # flake8-annotations
  "ASYNC", # flake8-async
  "S",     # flake8-bandit
  "BLE",   # flake8-blind-except
  "FBT",   # flake8-boolean-trap
  "B",     # flake8-bugbear
  "A",     # flake8-builtins
  "COM",   # flake8-commas
  "C4",    # flake8-comprehensions
  "DTZ",   # flake8-datetimez
  "EM",    # flake8-errmsg
  "FA",    # flake8-future-annotations
  "INT",   # flake8-gettext
  "ISC",   # flake8-implicit-str-concat
  "ICN",   # flake8-import-conventions
  "LOG",   # flake8-logging
  "G",     # flake8-logging-format
  "INP",   # flake8-no-pep420
  "PIE",   # flake8-pie
  "PYI",   # flake8-pyi
  "PT",    # flake8-pytest-style
  "Q",     # flake8-quotes
  "RSE",   # flake8-raise
  "RET",   # flake8-return
  "SLF",   # flake8-self
  "SIM",   # flake8-simplify
  "SLOT",  # flake8-slots
  "TID",   # flake8-tidy-imports
  "TC",    # flake8-type-checking
  "PTH",   # flake8-use-pathlib
  "FLY",   # flynt
  "I",     # isort
  "C90",   # mccabe
  "NPY",   # NumPy
  "PD",    # Pandas
  "N",     # pep8-naming
  "PERF",  # Perflint
  "E",     # pycodestyle Errors
  "W",     # pycodestyle Warnings
  "DOC",   # pydoclint
  "D",     # pydocstyle
  "F",     # pyflakes
  "PGH",   # pygrep-hooks
  "PLC",   # pylint conventions
  "PLE",   # pylint errors
  "PLR",   # pylint refactors
  "PLW",   # pylint warnings
  "UP",    # pyupgrade
  "FURB",  # refurb
  "RUF",   # ruff specific rules
  "TRY",   # tryceratops
]
