[project]
urls = { homepage = "http://www.control.lth.se/Staff/JerkerNordh/pyparticleest.html" }
dependencies = [
  "numpy>=2.1.2",
  "scipy>=1.14.1",
  "matplotlib>=3.9.2",
  "numba>=0.61.0,<0.63.0",
  "matplot2tikz",
  "latextable",
  "texttable",
]
name = "pyParticleEst"
authors = [{ email = "ajn@ajn.se", name = "Jerker Nordh" }]
description = "Framework for particle based estimation methods, such as particle filtering and smoothing"
license-files = ["COPYING"]
version = "1.1.4"
requires-python = ">=3.13"

[tool.setuptools]
packages = [
  "pyparticleest",
  "pyparticleest.models",
  "pyparticleest.paramest",
  "pyparticleest.utils",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "numpy>=2.1.2"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
docs = ["numpydoc>=1.7.0"]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = [
  "E",    # pycodestyle errors
  "F",    # Pyflakes
  "ANN",  # flake8-annotations
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "SIM",  # flake8-simplify
  "TC",   # flake8-type-checking
  "PTH",  # flake8-use-pathlib
  "I",    # isort
  "C90",  # mccabe
  "NPY",  # NumPy
  "PERF", # Perflint
  "E",    # pycodestyle Errors
  "W",    # pycodestyle Warnings
  "F",    # pyflakes
  "UP",   # pyupgrade
  "FURB", # refurb
  "RUF",  # ruff specific rules
]
